on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: Go Test
jobs:
    test:
        strategy:
            matrix:
                go-version: [1.11.x, 1.12.x, 1.13.x, 1.14.x]
                platform: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.platform }}
        steps:
            - name: Install Go ${{ matrix.go-version }}
              uses: actions/setup-go@v2
              with:
                  go-version: ${{ matrix.go-version }}
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Test on ${{ matrix.go-version }}
              run: go test -v ./...
